# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# [  ](fg:green)\
format = """
$os\
$directory \
($git_branch $git_commit ($git_state )$git_metrics$git_status)\
$fill\
$time
($sudo$hostname$username )$character
"""

palette = "catppuccin-mocha"
[palettes.catppuccin-mocha]
rosewater = "#F5E0DC"
flamingo = "#F2CDCD"
pink = "#F5C2E7"
mauve = "#CBA6F7"
red = "#F38BA8"
maroon = "#EBA0AC"
peach = "#FAB387"
yellow = "#F9E2AF"
green = "#A6E3A1"
teal = "#94E2D5"
sky = "#89DCEB"
sapphire = "#74C7EC"
cyan = "#00FFFF"
blue = "#89B4FA"
darkblue = "#545AA7"
lavender = "#B4BEFE"
text = "#CDD6F4"
subtext1 = "#BAC2DE"
subtext0 = "#A6ADC8"
overlay2 = "#9399b2"
overlay1 = "#7F849C"
surface2 = "#585B70"
surface1 = "#45475A"
surface0 = "#313244"
base = "#1E1E2E"
mantle = "#181825"
crust = "#11111B"

# [sudo]
# disabled = false
# symbol = "🥷"
# style = "bold bg:base"
# format = '[$symbol]($style)'

# One line prompt
[line_break]
disabled = true

[cmd_duration]
disabled = true

[os]
format = "[$symbol]($style)"
style = "bold green"
disabled = false

[os.symbols]
Macos = " "

[hostname]
disabled = false
ssh_only = false
ssh_symbol = " "
style = "bold bg:none fg:blue"
format = '[$ssh_symbol$hostname@]($style)'

[username]
disabled = false
show_always = true
style_root = "bold bg:none fg:red"
style_user = "bold bg:none fg:blue"
format = '[$user]($style)'

[directory]
disabled = false
home_symbol = "~"
truncate_to_repo = false
truncation_length = 99
truncation_symbol = ".../"
read_only = " "
style = "bold bg:none fg:cyan"
read_only_style = "fg:red"
format = '[$path]($style)[$readonly]($read_only_style)'

[aws]
format = 'on [$symbol($profile )(\($region\) )]($style)'
style = 'bold blue'
symbol = '🅰 '
[aws.region_aliases]
ap-southeast-2 = 'au'
us-east-1 = 'va'
[aws.profile_aliases]
CompanyGroupFrobozzOnCallAccess = 'Frobozz'

[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[env_var]
disabled = true
variable = "VIRTUAL_ENV"
symbol = ""
default = ""
style = "bold fg:text"
format = "[$env_value]($style)"

[git_branch]
disabled = false
symbol = ""
# symbol = ""
style = "bold bg:none fg:pink"
format = '[$symbol $branch(:$remote_branch)]($style)'

[git_commit]
disabled = false
only_detached = false
tag_disabled = false
tag_symbol = " 🏷 "
style = "bold bg:none fg:pink"
format = '[#$hash$tag]($style)'

[git_state]
disabled = false

[git_metrics]
disabled = false
added_style = "bold bg:none fg:green"
deleted_style = "bold bg:none fg:red"
format = '([+$added]($added_style) )([-$deleted]($deleted_style) )'

[git_status]
disabled = true
conflicted = '='
ahead = '⇡'
behind = '⇣'
diverged = '⇕'
up_to_date = ''
untracked = '?'
stashed = '\$'
modified = '!'
staged = '+'
renamed = '»'
deleted = '✘'
style = "bold bg:none fg:red"
format = '([\[$all_status$ahead_behind\]]($style) )'

[time]
disabled = true
# time_format = "%b %d, %T"
time_format = "%T"
style = "bold fg:yellow"
format = '[$time]($style)'

[fill]
disabled = false
symbol = " "

[character]
disabled = false
success_symbol = "[➜](bold fg:green)"
error_symbol = "[x](bold fg:red)"
# vicmd_symbol = "[➜](bold fg:mauve)"
format = "$symbol "

[package]
disabled = false
symbol = " "

[lua]
disabled = false
symbol = " "
format = '[\[$symbol$version\]]($style)'

[nodejs]
disabled = false
symbol = " "
format = '\[[$symbol($version)]($style)\]'

[hg_branch]
disabled = false
symbol = " "

[docker_context]
disabled = false
symbol = " "
