local colors = require("themes.feiyu.colors")

return {
  indent = {
    RainbowRed = { fg = colors.red_1 },
    RainbowYellow = { fg = colors.yellow },
    RainbowBlue = { fg = colors.blue },
    RainbowOrange = { fg = colors.orange },
    RainbowGreen = { fg = colors.green },
    RainbowViolet = { fg = colors.purple },
    RainbowCyan = { fg = colors.cyan },
  },
  pairs = {
    RainbowDelimiterRed = "RainbowRed",
    RainbowDelimiterBlue = "RainbowBlue",
    RainbowDelimiterCyan = "RainbowCyan",
    RainbowDelimiterGreen = "RainbowGreen",
    RainbowDelimiterOrange = "RainbowOrange",
    RainbowDelimiterViolet = "RainbowViolet",
    RainbowDelimiterYellow = "RainbowYellow",
  },
  blink = {
    indent = {
      BlinkIndentRed = "RainbowRed",
      BlinkIndentYellow = "RainbowYellow",
      BlinkIndentBlue = "RainbowBlue",
      BlinkIndentOrange = "RainbowOrange",
      BlinkIndentGreen = "RainbowGreen",
      BlinkIndentViolet = "RainbowViolet",
      BlinkIndentCyan = "RainbowCyan",
    },
    pairs = {
      BlinkPairsRed = "RainbowRed",
      BlinkPairsYellow = "RainbowYellow",
      BlinkPairsBlue = "RainbowBlue",
      BlinkPairsOrange = "RainbowOrange",
      BlinkPairsGreen = "RainbowGreen",
      BlinkPairsViolet = "RainbowViolet",
      BlinkPairsCyan = "RainbowCyan",
    },
    underline = {
      BlinkIndentRedUnderline = { sp = colors.red, underline = true },
      BlinkIndentYellowUnderline = { sp = colors.yellow, underline = true },
      BlinkIndentBlueUnderline = { sp = colors.blue, underline = true },
      BlinkIndentOrangeUnderline = { sp = colors.orange, underline = true },
      BlinkIndentGreenUnderline = { sp = colors.green, underline = true },
      BlinkIndentVioletUnderline = { sp = colors.purple, underline = true },
      BlinkIndentCyanUnderline = { sp = colors.cyan, underline = true },
    },
  },
  fold = {
    FoldLevel_1 = "RainbowOrange",
    FoldLevel_2 = "RainbowViolet",
    FoldLevel_3 = "RainbowBlue",
    FoldLevel_4 = "RainbowRed",
    FoldLevel_5 = "RainbowCyan",
    FoldLevel_6 = "RainbowYellow",
    FoldLevel_7 = "RainbowGreen",
  },
}
