---
style:
  tag:
    color: cyan
    width_percentage: 10
    min_width: 20
  comment:
    color: white
    width_percentage: 25
    min_width: 30
  snippet:
    color: blue
    width_percentage: 65

finder:
  command: skim

cheats:
  paths:
    - ~/.config/navi/cheats

# search:
#   tags: git,!checkout # equivalent to the --tag-rules option

client:
  tealdeer: true

shell:
  command: fish
