---
gui:
  timeFormat: "02 Jan 06 15:04 MST"
  theme:
    activeBorderColor:
      - "#00ffff"
      - bold
    inactiveBorderColor:
      - "#4E5BA6"
    optionsTextColor:
      - "#0089fc"
    selectedLineBgColor:
      - "#1d293d"
    selectedRangeBgColor:
      - "#1d293d"
    cherryPickedCommitBgColor:
      - "#94e2d5"
    cherryPickedCommitFgColor:
      - "#00a6f4"
    unstagedChangesColor:
      - "#B80000"
  nerdFontsVersion: "3"
  sidePanelWidth: 0.3
git:
  log:
    showGraph: always
    showWholeGraph: true
  paging:
    colorArg: always
    pager: delta --dark --paging=never
    # useConfig: true
  commit:
    signOff: false
    verbose: false
  branchLogCmd: "git log --graph --stat --oneline --color=always --decorate --pretty=format:'%Cblue %h %C(bold red)- <%an> -%C(green) (%ar)%C(auto)%d%n%C(yellow) %s'"
  diffContextSize: 3
  allBranchesLogCmds:
    - git log --graph --all --stat --oneline --color=always --decorate --pretty=format:'%Cblue %h %C(bold red)- <%an> -%C(green) (%ar)%C(auto)%d%n%C(yellow) %s'
os:
  edit: "nvim {{filename}}"
  editAtLine: "nvim +{{line}} {{filename}}"
  editAtLineAndWait: "nvim +{{line}} {{filename}}"
  editInTerminal: true
  openDirInEditor: "nvim {{dir}}"
