gui:
  timeFormat: "02 Jan 06 15:04 MST" # https://pkg.go.dev/time#Time.Format
  theme:
    activeBorderColor:
      - "#00ffff"
      - bold
    inactiveBorderColor:
      - "#3d59a1"
    optionsTextColor:
      - "#3B93F7"
    selectedLineBgColor:
      - "#3d59a1" # Surface0
    selectedRangeBgColor:
      - "#3d59a1" # Surface0
    cherryPickedCommitBgColor:
      - "#94e2d5" # Teal
    cherryPickedCommitFgColor:
      - "#89b4fa" # Blue
    unstagedChangesColor:
      - "#B80000"
  nerdFontsVersion: "3"
  sidePanelWidth: 0.3
git:
  log:
    showGraph: always
    showWholeGraph: true
  paging:
    colorArg: always
    pager: delta --dark --paging=never
    # useConfig: true
  commit:
    signOff: false
    verbose: false
  branchLogCmd: "git log --graph --stat --oneline --color=always --decorate --pretty=format:'%Cblue %h %C(bold red)- <%an> -%C(green) (%ar)%C(auto)%d%n%C(yellow) %s'"
  allBranchesLogCmd: "git log --graph --all --stat --oneline --color=always --decorate --pretty=format:'%Cblue %h %C(bold red)- <%an> -%C(green) (%ar)%C(auto)%d%n%C(yellow) %s'"
  diffContextSize: 3 # how many lines of context are shown around a change in diffs
os:
  edit: "nvim {{filename}}"
  editAtLine: "nvim +{{line}} {{filename}}"
  editAtLineAndWait: "nvim +{{line}} {{filename}}"
  editInTerminal: true
  openDirInEditor: "nvim {{dir}}"
