local icons = {
  Kind = {
    Array = " ",
    Boolean = " ",
    Class = " ",
    Color = " ",
    Constant = " ",
    Copilot = " ",
    Event = " ",
    Field = " ",
    File = " ",
    Folder = " ",
    Function = "󰊕 ",
    Key = " ",
    Keyword = " ",
    Method = " ",
    Module = "󰕳 ",
    Namespace = " ",
    Null = "󰟢 ",
    Number = " ",
    Object = " ",
    Operator = " ",
    Package = " ",
    Property = " ",
    Reference = " ",
    Snippet = " ",
    String = " ",
    Struct = " ",
    TypeParameter = " ",
    Unit = " ",
    Value = " ",
    Variable = " ",
    Text = " ",
    Constructor = " ",
    Interface = " ",
    Enum = " ",
    EnumMember = " ",
  },
  Cmp = {
    Path = "  ",
    Snippet = "  ",
    Lsp = "  ",
    NvimLua = " 󰢱 ",
    Tabnine = "  ",
    Buffer = "  ",
    Tree = "  ",
    Spellcheck = " 󰓆 ",
  },
  UI = {
    Apple = "󰀵",
    Vim = "",
    Code = "",
    Close = "󰅖",
    Telescope = "",
    TaskList = "",
    TextSize = "",
    Menu = "",
    Search = " ",
    Ellipsis = "",
    Check = "",
    Sort = "󰒺",
    Session = "󱂬",
    Tab = "󰓩",
    TabClose = "󰅙",
    Circle = "",
    SelectionCaret = " ",
    Terminal = {
      Icon = "",
      Icon2 = "",
      Bash = "",
      Linux = "",
      Tmux = "",
      PowerShell = "",
      Cmd = "",
    },
    Folder = {
      Empty = "",
      EmptyOpen = "",
      Icon = "󰉋",
      Open = "",
      Edit = "󰣞",
      Remove = "󰉘",
      Upload = "󰉙",
      Download = "󰉍",
      Image = "󰉏",
      Move = "󰉒",
      Lock = "󰉐",
      Unlock = "󰉑",
      Submodule = "",
      Check = "󱥾",
      Cancel = "󱧴",
    },
    Line = {
      Left = "▏",
      Mid = "│",
      Right = "▕",
      BoldMid = "┃",
      BoldLeft = "▎",
    },
    List = {
      Icon = "",
      Filter = "",
      Selection = "",
      Flat = "",
      Tree = "",
      Ordered = "",
      Unordered = "",
    },
    Direction = {
      Chevron = {
        Down = "",
        Left = "",
        Right = "",
        Up = "",
        DownBold = "",
        UpBold = "",
        LeftBold = "",
        RightBold = "",
        DownMd = "󰅀",
        UpMd = "󰅃",
        LeftMd = "󰅁",
        RightMd = "󰅂",
        DownOct = "",
        UpOct = "",
        LeftOct = "",
        RightOct = "",
      },
      Angle = {
        Down = "",
        Left = "",
        Right = "",
        Up = "",
      },
      Triangle = {
        Down = "",
        Left = "",
        Right = "",
        Up = "",
      },
      Arrow = {
        Down = "",
        Left = "",
        Right = "",
        Up = "",
        DownMd = "󰁅",
        LeftMd = "󰁍",
        RightMd = "󰁔",
        UpMd = "󰁝",
      },
    },
  },
  Diagnostics = {
    Error = "",
    Warning = "󰗖",
    Information = "",
    Hint = "󰌶",

    BoldError = "",
    BoldWarning = "",
    BoldInformation = "",
    BoldHint = "󰌵",

    Question = "",
    BoldQuestion = "",

    TriangleWarning = "",
    BoldTriangleWarning = "",

    Debug = "",
    Trace = "✎",
    BoldDebug = "",
  },
  Git = {
    Gitlab = "",
    Github = "",
    Branch = "",
    Commit = "",
    Compare = "",
    Merge = "",
    Folder = "",
    Pull = "",
    Forked = "",
    Repo = "",

    LineAdded = "",
    LineModified = "",
    LineRemoved = "",
    LineIgnore = "",
    LineRename = "",
    FileIgnored = "◌",
    FileDeleted = "",
    FileRenamed = "󰑕",
    FileStaged = "",
    FileUnmerged = "",
    FileUnstaged = "",
    FileUntracked = "",
    Diff = "",
  },
}

return icons
