local icons = require("icons")
HVIM = {
  colorscheme = "eryx",
  leader = " ",
  use_icons = true,
  icons = icons,
  builtin = {},
  competitive_programming = false,
  signs = {
    Error = icons.Diagnostics.Error,
    Warn = icons.Diagnostics.Warning,
    Hint = icons.Diagnostics.Hint,
    Info = icons.Diagnostics.Information,
  },
  bold_signs = {
    error = icons.Diagnostics.BoldError,
    warning = icons.Diagnostics.BoldWarning,
    warn = icons.Diagnostics.BoldWarning,
    info = icons.Diagnostics.BoldInformation,
    hint = icons.Diagnostics.BoldHint,
  },
  git_line = {
    added = icons.Git.LineAdded .. " ",
    changed = icons.Git.LineModified .. " ",
    removed = icons.Git.LineRemoved .. " ",
  },
  highlight = {
    fold = false,
    indent = true,
  },
  plugins = {
    alpha = true,
    blink = true,
    blink_nvim = true,
    blink_pairs = true,
    blink_indent = true,
    blink_cmp = true,
    mini_icon = true,
    eyeliner = true,
    lualine = false,
    statuscol = true,
    statusline = true,
    winbar = true,
    navic = false,
    buffer = false,
    neotree = true,
    bufferline = true,
    treesitter = true,
    lsp = true,
    telescope = false,
    git = true,
    fzf = true,
    none_ls = false,
  },
  ui = {
    colors = {
      "#fc5f66",
      "#FFEB0A",
      "#3B93F7",
      "#fb8500",
      "#ccff33",
      "#b67cff",
      "#00FFFF",
      "#f984d4",
      "#E8E2D9",
      "#a0aacc",
    },
  },
}
