vim.cmd([[hi NeoTreeCursorLine gui=NONE guibg=#292e42]])
vim.cmd([[hi CursorLine gui=underline]])
vim.cmd([[hi FloatShadow guibg=NONE]])
vim.cmd([[hi FloatShadowThrough guibg=NONE]])
vim.cmd([[hi QuickScopePrimary guifg=#ff7788 ctermfg=155]])
vim.cmd([[hi QuickScopeSecondary guifg=#afff5f ctermfg=81]])
