require 'plugins.paq-nvim'
require 'plugins.tree'
require 'plugins.nvim-webdev-icons'
require 'plugins.lualine'
require 'plugins.indent-blankline'
require 'plugins.bufferline'
-- require 'plugins.neoscroll'
require 'plugins.telescope'
require 'plugins.autocommands'
require 'plugins.illuminate'

-- Config colors
require 'plugins.colors'
require 'plugins.autopairs'
-- require 'plugins.highlight'

-- require 'plugins.tabnine'
require 'plugins.trouble'
require 'plugins.lsp'
require 'plugins.treesister'
